name: License

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
      with:
        persist-credentials: false
      
    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # tag=v5.4.0
      with:
        go-version-file: 'go.mod'

    - name: Check License Headers
      run: go run github.com/google/addlicense@dc31ac9ffcca99c9457226366135701794b128c0 -check -l apache ** # tag=v1.1.1


  
  
